// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: scanner.proto

package scannerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScanRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// request_id correlates this scan with the proxy request.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// content is the raw request body to scan.
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// enabled_scanners restricts which scanners run. Empty means all registered.
	EnabledScanners []string `protobuf:"bytes,3,rep,name=enabled_scanners,json=enabledScanners,proto3" json:"enabled_scanners,omitempty"`
	// pipeline_mode selects execution strategy: "adaptive", "sync", "async", or "workerpool".
	PipelineMode string `protobuf:"bytes,4,opt,name=pipeline_mode,json=pipelineMode,proto3" json:"pipeline_mode,omitempty"`
	// metadata carries optional key-value pairs (e.g. trace context).
	Metadata      map[string]string `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	mi := &file_scanner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{0}
}

func (x *ScanRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ScanRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ScanRequest) GetEnabledScanners() []string {
	if x != nil {
		return x.EnabledScanners
	}
	return nil
}

func (x *ScanRequest) GetPipelineMode() string {
	if x != nil {
		return x.PipelineMode
	}
	return ""
}

func (x *ScanRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ScanResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Findings  []*Finding             `protobuf:"bytes,2,rep,name=findings,proto3" json:"findings,omitempty"`
	// scanner_results maps scanner name → per-scanner outcome.
	ScannerResults map[string]*ScannerResult `protobuf:"bytes,3,rep,name=scanner_results,json=scannerResults,proto3" json:"scanner_results,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// duration_ms is the total scan phase wall-clock time in milliseconds.
	DurationMs    float64 `protobuf:"fixed64,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResponse) Reset() {
	*x = ScanResponse{}
	mi := &file_scanner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResponse) ProtoMessage() {}

func (x *ScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResponse.ProtoReflect.Descriptor instead.
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{1}
}

func (x *ScanResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ScanResponse) GetFindings() []*Finding {
	if x != nil {
		return x.Findings
	}
	return nil
}

func (x *ScanResponse) GetScannerResults() map[string]*ScannerResult {
	if x != nil {
		return x.ScannerResults
	}
	return nil
}

func (x *ScanResponse) GetDurationMs() float64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

// Finding represents a single security detection, mirroring the Go Finding
// struct at proxy/internal/scanner/scanner.go:10.
type Finding struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Type           string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Severity       string                 `protobuf:"bytes,2,opt,name=severity,proto3" json:"severity,omitempty"`
	Match          string                 `protobuf:"bytes,3,opt,name=match,proto3" json:"match,omitempty"`
	Category       string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	StartPos       int32                  `protobuf:"varint,5,opt,name=start_pos,json=startPos,proto3" json:"start_pos,omitempty"`
	EndPos         int32                  `protobuf:"varint,6,opt,name=end_pos,json=endPos,proto3" json:"end_pos,omitempty"`
	Confidence     float64                `protobuf:"fixed64,7,opt,name=confidence,proto3" json:"confidence,omitempty"`
	ActionTaken    string                 `protobuf:"bytes,8,opt,name=action_taken,json=actionTaken,proto3" json:"action_taken,omitempty"`
	Metadata       map[string]string      `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ScannerVersion string                 `protobuf:"bytes,10,opt,name=scanner_version,json=scannerVersion,proto3" json:"scanner_version,omitempty"`
	DatasetVersion string                 `protobuf:"bytes,11,opt,name=dataset_version,json=datasetVersion,proto3" json:"dataset_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Finding) Reset() {
	*x = Finding{}
	mi := &file_scanner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Finding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Finding) ProtoMessage() {}

func (x *Finding) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Finding.ProtoReflect.Descriptor instead.
func (*Finding) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{2}
}

func (x *Finding) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Finding) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Finding) GetMatch() string {
	if x != nil {
		return x.Match
	}
	return ""
}

func (x *Finding) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Finding) GetStartPos() int32 {
	if x != nil {
		return x.StartPos
	}
	return 0
}

func (x *Finding) GetEndPos() int32 {
	if x != nil {
		return x.EndPos
	}
	return 0
}

func (x *Finding) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Finding) GetActionTaken() string {
	if x != nil {
		return x.ActionTaken
	}
	return ""
}

func (x *Finding) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Finding) GetScannerVersion() string {
	if x != nil {
		return x.ScannerVersion
	}
	return ""
}

func (x *Finding) GetDatasetVersion() string {
	if x != nil {
		return x.DatasetVersion
	}
	return ""
}

// ScannerResult captures per-scanner execution outcome.
type ScannerResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// succeeded is true when the scanner ran without error.
	Succeeded bool `protobuf:"varint,1,opt,name=succeeded,proto3" json:"succeeded,omitempty"`
	// error contains the error message when succeeded is false.
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// duration_ms is the wall-clock time for this specific scanner.
	DurationMs float64 `protobuf:"fixed64,3,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	// finding_count is how many findings this scanner produced.
	FindingCount  int32 `protobuf:"varint,4,opt,name=finding_count,json=findingCount,proto3" json:"finding_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScannerResult) Reset() {
	*x = ScannerResult{}
	mi := &file_scanner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScannerResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScannerResult) ProtoMessage() {}

func (x *ScannerResult) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScannerResult.ProtoReflect.Descriptor instead.
func (*ScannerResult) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{3}
}

func (x *ScannerResult) GetSucceeded() bool {
	if x != nil {
		return x.Succeeded
	}
	return false
}

func (x *ScannerResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ScannerResult) GetDurationMs() float64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *ScannerResult) GetFindingCount() int32 {
	if x != nil {
		return x.FindingCount
	}
	return 0
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_scanner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{4}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`   // "SERVING" | "NOT_SERVING"
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"` // "tamga-scanner"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_scanner_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{5}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

var File_scanner_proto protoreflect.FileDescriptor

const file_scanner_proto_rawDesc = "" +
	"\n" +
	"\rscanner.proto\x12\x10tamga.scanner.v1\"\x9c\x02\n" +
	"\vScanRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12)\n" +
	"\x10enabled_scanners\x18\x03 \x03(\tR\x0fenabledScanners\x12#\n" +
	"\rpipeline_mode\x18\x04 \x01(\tR\fpipelineMode\x12G\n" +
	"\bmetadata\x18\x05 \x03(\v2+.tamga.scanner.v1.ScanRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc6\x02\n" +
	"\fScanResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x125\n" +
	"\bfindings\x18\x02 \x03(\v2\x19.tamga.scanner.v1.FindingR\bfindings\x12[\n" +
	"\x0fscanner_results\x18\x03 \x03(\v22.tamga.scanner.v1.ScanResponse.ScannerResultsEntryR\x0escannerResults\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x01R\n" +
	"durationMs\x1ab\n" +
	"\x13ScannerResultsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.tamga.scanner.v1.ScannerResultR\x05value:\x028\x01\"\xb8\x03\n" +
	"\aFinding\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1a\n" +
	"\bseverity\x18\x02 \x01(\tR\bseverity\x12\x14\n" +
	"\x05match\x18\x03 \x01(\tR\x05match\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x1b\n" +
	"\tstart_pos\x18\x05 \x01(\x05R\bstartPos\x12\x17\n" +
	"\aend_pos\x18\x06 \x01(\x05R\x06endPos\x12\x1e\n" +
	"\n" +
	"confidence\x18\a \x01(\x01R\n" +
	"confidence\x12!\n" +
	"\faction_taken\x18\b \x01(\tR\vactionTaken\x12C\n" +
	"\bmetadata\x18\t \x03(\v2'.tamga.scanner.v1.Finding.MetadataEntryR\bmetadata\x12'\n" +
	"\x0fscanner_version\x18\n" +
	" \x01(\tR\x0escannerVersion\x12'\n" +
	"\x0fdataset_version\x18\v \x01(\tR\x0edatasetVersion\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x89\x01\n" +
	"\rScannerResult\x12\x1c\n" +
	"\tsucceeded\x18\x01 \x01(\bR\tsucceeded\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1f\n" +
	"\vduration_ms\x18\x03 \x01(\x01R\n" +
	"durationMs\x12#\n" +
	"\rfinding_count\x18\x04 \x01(\x05R\ffindingCount\"\x0f\n" +
	"\rHealthRequest\"B\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice2\xa9\x01\n" +
	"\x0eScannerService\x12E\n" +
	"\x04Scan\x12\x1d.tamga.scanner.v1.ScanRequest\x1a\x1e.tamga.scanner.v1.ScanResponse\x12P\n" +
	"\vHealthCheck\x12\x1f.tamga.scanner.v1.HealthRequest\x1a .tamga.scanner.v1.HealthResponseB=Z;github.com/yatuk/tamga/proto/scanner/v1;scannerv1b\x06proto3"

var (
	file_scanner_proto_rawDescOnce sync.Once
	file_scanner_proto_rawDescData []byte
)

func file_scanner_proto_rawDescGZIP() []byte {
	file_scanner_proto_rawDescOnce.Do(func() {
		file_scanner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scanner_proto_rawDesc), len(file_scanner_proto_rawDesc)))
	})
	return file_scanner_proto_rawDescData
}

var file_scanner_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_scanner_proto_goTypes = []any{
	(*ScanRequest)(nil),    // 0: tamga.scanner.v1.ScanRequest
	(*ScanResponse)(nil),   // 1: tamga.scanner.v1.ScanResponse
	(*Finding)(nil),        // 2: tamga.scanner.v1.Finding
	(*ScannerResult)(nil),  // 3: tamga.scanner.v1.ScannerResult
	(*HealthRequest)(nil),  // 4: tamga.scanner.v1.HealthRequest
	(*HealthResponse)(nil), // 5: tamga.scanner.v1.HealthResponse
	nil,                    // 6: tamga.scanner.v1.ScanRequest.MetadataEntry
	nil,                    // 7: tamga.scanner.v1.ScanResponse.ScannerResultsEntry
	nil,                    // 8: tamga.scanner.v1.Finding.MetadataEntry
}
var file_scanner_proto_depIdxs = []int32{
	6, // 0: tamga.scanner.v1.ScanRequest.metadata:type_name -> tamga.scanner.v1.ScanRequest.MetadataEntry
	2, // 1: tamga.scanner.v1.ScanResponse.findings:type_name -> tamga.scanner.v1.Finding
	7, // 2: tamga.scanner.v1.ScanResponse.scanner_results:type_name -> tamga.scanner.v1.ScanResponse.ScannerResultsEntry
	8, // 3: tamga.scanner.v1.Finding.metadata:type_name -> tamga.scanner.v1.Finding.MetadataEntry
	3, // 4: tamga.scanner.v1.ScanResponse.ScannerResultsEntry.value:type_name -> tamga.scanner.v1.ScannerResult
	0, // 5: tamga.scanner.v1.ScannerService.Scan:input_type -> tamga.scanner.v1.ScanRequest
	4, // 6: tamga.scanner.v1.ScannerService.HealthCheck:input_type -> tamga.scanner.v1.HealthRequest
	1, // 7: tamga.scanner.v1.ScannerService.Scan:output_type -> tamga.scanner.v1.ScanResponse
	5, // 8: tamga.scanner.v1.ScannerService.HealthCheck:output_type -> tamga.scanner.v1.HealthResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_scanner_proto_init() }
func file_scanner_proto_init() {
	if File_scanner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scanner_proto_rawDesc), len(file_scanner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scanner_proto_goTypes,
		DependencyIndexes: file_scanner_proto_depIdxs,
		MessageInfos:      file_scanner_proto_msgTypes,
	}.Build()
	File_scanner_proto = out.File
	file_scanner_proto_goTypes = nil
	file_scanner_proto_depIdxs = nil
}
