apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tamga-proxy.fullname" . }}-policy
  labels: {{- include "tamga-proxy.labels" . | nindent 4 }}
data:
  policy.yaml: |
{{ .Values.policy.inline | indent 4 }}
