# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from analyzer.v1 import tamga_pb2 as analyzer_dot_v1_dot_tamga__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in analyzer/v1/tamga_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AnalyzerServiceStub:
    """── AnalyzerService ─────────────────────────────────────────────────────────
    Deep semantic NLP analysis for LLM security scanning.

    Called by the Go proxy AFTER static regex scanning completes. The Go proxy
    has already detected and redacted/blocked based on regex patterns. This
    service provides the ML/NLP layer: Presidio spaCy NER, Claude Haiku judge,
    and LLM Guard ML classifiers.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Analyze = channel.unary_unary(
                '/proto.analyzer.v1.AnalyzerService/Analyze',
                request_serializer=analyzer_dot_v1_dot_tamga__pb2.AnalyzeRequest.SerializeToString,
                response_deserializer=analyzer_dot_v1_dot_tamga__pb2.AnalyzeResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/proto.analyzer.v1.AnalyzerService/HealthCheck',
                request_serializer=analyzer_dot_v1_dot_tamga__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=analyzer_dot_v1_dot_tamga__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class AnalyzerServiceServicer:
    """── AnalyzerService ─────────────────────────────────────────────────────────
    Deep semantic NLP analysis for LLM security scanning.

    Called by the Go proxy AFTER static regex scanning completes. The Go proxy
    has already detected and redacted/blocked based on regex patterns. This
    service provides the ML/NLP layer: Presidio spaCy NER, Claude Haiku judge,
    and LLM Guard ML classifiers.

    """

    def Analyze(self, request, context):
        """Analyze runs deep semantic analysis on content that has already passed
        the Go proxy's static regex scanners. Returns only NLP/ML findings.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """HealthCheck returns service health status (standard gRPC health probe).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalyzerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Analyze': grpc.unary_unary_rpc_method_handler(
                    servicer.Analyze,
                    request_deserializer=analyzer_dot_v1_dot_tamga__pb2.AnalyzeRequest.FromString,
                    response_serializer=analyzer_dot_v1_dot_tamga__pb2.AnalyzeResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=analyzer_dot_v1_dot_tamga__pb2.HealthCheckRequest.FromString,
                    response_serializer=analyzer_dot_v1_dot_tamga__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.analyzer.v1.AnalyzerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.analyzer.v1.AnalyzerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnalyzerService:
    """── AnalyzerService ─────────────────────────────────────────────────────────
    Deep semantic NLP analysis for LLM security scanning.

    Called by the Go proxy AFTER static regex scanning completes. The Go proxy
    has already detected and redacted/blocked based on regex patterns. This
    service provides the ML/NLP layer: Presidio spaCy NER, Claude Haiku judge,
    and LLM Guard ML classifiers.

    """

    @staticmethod
    def Analyze(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.analyzer.v1.AnalyzerService/Analyze',
            analyzer_dot_v1_dot_tamga__pb2.AnalyzeRequest.SerializeToString,
            analyzer_dot_v1_dot_tamga__pb2.AnalyzeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.analyzer.v1.AnalyzerService/HealthCheck',
            analyzer_dot_v1_dot_tamga__pb2.HealthCheckRequest.SerializeToString,
            analyzer_dot_v1_dot_tamga__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
