// Tamga Classifier — gRPC API of the prompt-injection classifier service.
//
// Unlike the analyzer, this service is on the decision path: the proxy calls
// it inline, under a short deadline, when its own rules found nothing
// conclusive. It runs a local ONNX model on CPU and holds no other state.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: classifier/v1/classifier.proto

package classifierv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClassifyRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Texts to score, one per segment of the request.
	Texts         []string `protobuf:"bytes,2,rep,name=texts,proto3" json:"texts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassifyRequest) Reset() {
	*x = ClassifyRequest{}
	mi := &file_classifier_v1_classifier_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyRequest) ProtoMessage() {}

func (x *ClassifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_classifier_v1_classifier_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyRequest.ProtoReflect.Descriptor instead.
func (*ClassifyRequest) Descriptor() ([]byte, []int) {
	return file_classifier_v1_classifier_proto_rawDescGZIP(), []int{0}
}

func (x *ClassifyRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ClassifyRequest) GetTexts() []string {
	if x != nil {
		return x.Texts
	}
	return nil
}

type ClassifyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Probability that each text is an injection attempt, in request order.
	Scores []float32 `protobuf:"fixed32,1,rep,packed,name=scores,proto3" json:"scores,omitempty"`
	// True for a text too long to score whole: only its first windows were
	// read, so a low score does not mean it is clean.
	Truncated []bool `protobuf:"varint,2,rep,packed,name=truncated,proto3" json:"truncated,omitempty"`
	// Name of the loaded model (its directory name).
	Model         string  `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	DurationMs    float64 `protobuf:"fixed64,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassifyResponse) Reset() {
	*x = ClassifyResponse{}
	mi := &file_classifier_v1_classifier_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyResponse) ProtoMessage() {}

func (x *ClassifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_classifier_v1_classifier_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyResponse.ProtoReflect.Descriptor instead.
func (*ClassifyResponse) Descriptor() ([]byte, []int) {
	return file_classifier_v1_classifier_proto_rawDescGZIP(), []int{1}
}

func (x *ClassifyResponse) GetScores() []float32 {
	if x != nil {
		return x.Scores
	}
	return nil
}

func (x *ClassifyResponse) GetTruncated() []bool {
	if x != nil {
		return x.Truncated
	}
	return nil
}

func (x *ClassifyResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ClassifyResponse) GetDurationMs() float64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_classifier_v1_classifier_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_classifier_v1_classifier_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_classifier_v1_classifier_proto_rawDescGZIP(), []int{2}
}

type HealthResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Available bool                   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	Model     string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	// Why no model is loaded, when available is false.
	Reason        string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_classifier_v1_classifier_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_classifier_v1_classifier_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_classifier_v1_classifier_proto_rawDescGZIP(), []int{3}
}

func (x *HealthResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *HealthResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *HealthResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_classifier_v1_classifier_proto protoreflect.FileDescriptor

const file_classifier_v1_classifier_proto_rawDesc = "" +
	"\n" +
	"\x1eclassifier/v1/classifier.proto\x12\x13proto.classifier.v1\"F\n" +
	"\x0fClassifyRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x14\n" +
	"\x05texts\x18\x02 \x03(\tR\x05texts\"\x7f\n" +
	"\x10ClassifyResponse\x12\x16\n" +
	"\x06scores\x18\x01 \x03(\x02R\x06scores\x12\x1c\n" +
	"\ttruncated\x18\x02 \x03(\bR\ttruncated\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x01R\n" +
	"durationMs\"\x0f\n" +
	"\rHealthRequest\"\\\n" +
	"\x0eHealthResponse\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason2\xbf\x01\n" +
	"\x11ClassifierService\x12W\n" +
	"\bClassify\x12$.proto.classifier.v1.ClassifyRequest\x1a%.proto.classifier.v1.ClassifyResponse\x12Q\n" +
	"\x06Health\x12\".proto.classifier.v1.HealthRequest\x1a#.proto.classifier.v1.HealthResponseB9Z7github.com/yatuk/tamga/proto/classifier/v1;classifierv1b\x06proto3"

var (
	file_classifier_v1_classifier_proto_rawDescOnce sync.Once
	file_classifier_v1_classifier_proto_rawDescData []byte
)

func file_classifier_v1_classifier_proto_rawDescGZIP() []byte {
	file_classifier_v1_classifier_proto_rawDescOnce.Do(func() {
		file_classifier_v1_classifier_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_classifier_v1_classifier_proto_rawDesc), len(file_classifier_v1_classifier_proto_rawDesc)))
	})
	return file_classifier_v1_classifier_proto_rawDescData
}

var file_classifier_v1_classifier_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_classifier_v1_classifier_proto_goTypes = []any{
	(*ClassifyRequest)(nil),  // 0: proto.classifier.v1.ClassifyRequest
	(*ClassifyResponse)(nil), // 1: proto.classifier.v1.ClassifyResponse
	(*HealthRequest)(nil),    // 2: proto.classifier.v1.HealthRequest
	(*HealthResponse)(nil),   // 3: proto.classifier.v1.HealthResponse
}
var file_classifier_v1_classifier_proto_depIdxs = []int32{
	0, // 0: proto.classifier.v1.ClassifierService.Classify:input_type -> proto.classifier.v1.ClassifyRequest
	2, // 1: proto.classifier.v1.ClassifierService.Health:input_type -> proto.classifier.v1.HealthRequest
	1, // 2: proto.classifier.v1.ClassifierService.Classify:output_type -> proto.classifier.v1.ClassifyResponse
	3, // 3: proto.classifier.v1.ClassifierService.Health:output_type -> proto.classifier.v1.HealthResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_classifier_v1_classifier_proto_init() }
func file_classifier_v1_classifier_proto_init() {
	if File_classifier_v1_classifier_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_classifier_v1_classifier_proto_rawDesc), len(file_classifier_v1_classifier_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_classifier_v1_classifier_proto_goTypes,
		DependencyIndexes: file_classifier_v1_classifier_proto_depIdxs,
		MessageInfos:      file_classifier_v1_classifier_proto_msgTypes,
	}.Build()
	File_classifier_v1_classifier_proto = out.File
	file_classifier_v1_classifier_proto_goTypes = nil
	file_classifier_v1_classifier_proto_depIdxs = nil
}
