# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analyzer/v1/tamga.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'analyzer/v1/tamga.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x61nalyzer/v1/tamga.proto\x12\x11proto.analyzer.v1\"\xf3\x01\n\x0e\x41nalyzeRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x12\n\nscan_types\x18\x03 \x03(\t\x12\x10\n\x08provider\x18\x04 \x01(\t\x12\r\n\x05model\x18\x05 \x01(\t\x12\x41\n\x08metadata\x18\x06 \x03(\x0b\x32/.proto.analyzer.v1.AnalyzeRequest.MetadataEntry\x12\x13\n\x0bpre_scanned\x18\x07 \x01(\x08\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xa3\x01\n\x0f\x41nalyzeResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12,\n\x08\x66indings\x18\x02 \x03(\x0b\x32\x1a.proto.analyzer.v1.Finding\x12\x13\n\x0b\x64uration_ms\x18\x03 \x01(\x01\x12\x39\n\x0fscanner_results\x18\x04 \x03(\x0b\x32 .proto.analyzer.v1.ScannerResult\"^\n\x07\x46inding\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x02 \x01(\t\x12\x10\n\x08severity\x18\x03 \x01(\t\x12\r\n\x05match\x18\x04 \x01(\t\x12\x12\n\nconfidence\x18\x05 \x01(\x01\"c\n\rScannerResult\x12\x0f\n\x07scanner\x18\x01 \x01(\t\x12,\n\x08\x66indings\x18\x02 \x03(\x0b\x32\x1a.proto.analyzer.v1.Finding\x12\x13\n\x0b\x64uration_ms\x18\x03 \x01(\x01\"\x14\n\x12HealthCheckRequest\"6\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07service\x18\x02 \x01(\t2\xc1\x01\n\x0f\x41nalyzerService\x12P\n\x07\x41nalyze\x12!.proto.analyzer.v1.AnalyzeRequest\x1a\".proto.analyzer.v1.AnalyzeResponse\x12\\\n\x0bHealthCheck\x12%.proto.analyzer.v1.HealthCheckRequest\x1a&.proto.analyzer.v1.HealthCheckResponseB?Z=github.com/yatuk/tamga/proto/analyzer/v1;analyzerv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analyzer.v1.tamga_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z=github.com/yatuk/tamga/proto/analyzer/v1;analyzerv1'
  _globals['_ANALYZEREQUEST_METADATAENTRY']._loaded_options = None
  _globals['_ANALYZEREQUEST_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_ANALYZEREQUEST']._serialized_start=47
  _globals['_ANALYZEREQUEST']._serialized_end=290
  _globals['_ANALYZEREQUEST_METADATAENTRY']._serialized_start=243
  _globals['_ANALYZEREQUEST_METADATAENTRY']._serialized_end=290
  _globals['_ANALYZERESPONSE']._serialized_start=293
  _globals['_ANALYZERESPONSE']._serialized_end=456
  _globals['_FINDING']._serialized_start=458
  _globals['_FINDING']._serialized_end=552
  _globals['_SCANNERRESULT']._serialized_start=554
  _globals['_SCANNERRESULT']._serialized_end=653
  _globals['_HEALTHCHECKREQUEST']._serialized_start=655
  _globals['_HEALTHCHECKREQUEST']._serialized_end=675
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=677
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=731
  _globals['_ANALYZERSERVICE']._serialized_start=734
  _globals['_ANALYZERSERVICE']._serialized_end=927
# @@protoc_insertion_point(module_scope)
