// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: analyzer/v1/tamga.proto

package analyzerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalyzeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique request identifier propagated from the proxy (UUID).
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// The text content to analyze (prompt or response body).
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// Which scanner types to run: "pii", "injection", "toxicity".
	// The Go proxy selects these based on input risk score.
	ScanTypes []string `protobuf:"bytes,3,rep,name=scan_types,json=scanTypes,proto3" json:"scan_types,omitempty"`
	// LLM provider and model (e.g. "openai", "gpt-4o-mini").
	Provider string `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`
	Model    string `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	// Opaque metadata forwarded from the proxy (org_id, action, endpoint,
	// direction, input_risk, etc.).
	Metadata map[string]string `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Set by the Go proxy; text has already passed static regex scan.
	PreScanned    bool `protobuf:"varint,7,opt,name=pre_scanned,json=preScanned,proto3" json:"pre_scanned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeRequest) Reset() {
	*x = AnalyzeRequest{}
	mi := &file_analyzer_v1_tamga_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeRequest) ProtoMessage() {}

func (x *AnalyzeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analyzer_v1_tamga_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeRequest) Descriptor() ([]byte, []int) {
	return file_analyzer_v1_tamga_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AnalyzeRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AnalyzeRequest) GetScanTypes() []string {
	if x != nil {
		return x.ScanTypes
	}
	return nil
}

func (x *AnalyzeRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *AnalyzeRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AnalyzeRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AnalyzeRequest) GetPreScanned() bool {
	if x != nil {
		return x.PreScanned
	}
	return false
}

type AnalyzeResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Aggregated findings from all scanners.
	Findings []*Finding `protobuf:"bytes,2,rep,name=findings,proto3" json:"findings,omitempty"`
	// End-to-end wall-clock duration in milliseconds.
	DurationMs float64 `protobuf:"fixed64,3,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	// Per-scanner results for observability (duration, count per scanner).
	ScannerResults []*ScannerResult `protobuf:"bytes,4,rep,name=scanner_results,json=scannerResults,proto3" json:"scanner_results,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AnalyzeResponse) Reset() {
	*x = AnalyzeResponse{}
	mi := &file_analyzer_v1_tamga_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeResponse) ProtoMessage() {}

func (x *AnalyzeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analyzer_v1_tamga_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeResponse) Descriptor() ([]byte, []int) {
	return file_analyzer_v1_tamga_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyzeResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AnalyzeResponse) GetFindings() []*Finding {
	if x != nil {
		return x.Findings
	}
	return nil
}

func (x *AnalyzeResponse) GetDurationMs() float64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *AnalyzeResponse) GetScannerResults() []*ScannerResult {
	if x != nil {
		return x.ScannerResults
	}
	return nil
}

type Finding struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Finding type: "pii", "injection", "toxicity".
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Entity/technique category (e.g. "PERSON", "ignore_prev", "toxicity").
	Category string `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	// Severity level: "critical", "high", "medium", "low".
	Severity string `protobuf:"bytes,3,opt,name=severity,proto3" json:"severity,omitempty"`
	// Truncated match excerpt for logging/audit (≤200 chars).
	Match string `protobuf:"bytes,4,opt,name=match,proto3" json:"match,omitempty"`
	// Confidence score 0.0–1.0.
	Confidence    float64 `protobuf:"fixed64,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Finding) Reset() {
	*x = Finding{}
	mi := &file_analyzer_v1_tamga_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Finding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Finding) ProtoMessage() {}

func (x *Finding) ProtoReflect() protoreflect.Message {
	mi := &file_analyzer_v1_tamga_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Finding.ProtoReflect.Descriptor instead.
func (*Finding) Descriptor() ([]byte, []int) {
	return file_analyzer_v1_tamga_proto_rawDescGZIP(), []int{2}
}

func (x *Finding) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Finding) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Finding) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Finding) GetMatch() string {
	if x != nil {
		return x.Match
	}
	return ""
}

func (x *Finding) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type ScannerResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Scanner name (e.g. "pii_deep", "injection_llm", "toxicity").
	Scanner string `protobuf:"bytes,1,opt,name=scanner,proto3" json:"scanner,omitempty"`
	// Findings produced by this scanner.
	Findings []*Finding `protobuf:"bytes,2,rep,name=findings,proto3" json:"findings,omitempty"`
	// Scanner execution time in milliseconds.
	DurationMs    float64 `protobuf:"fixed64,3,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScannerResult) Reset() {
	*x = ScannerResult{}
	mi := &file_analyzer_v1_tamga_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScannerResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScannerResult) ProtoMessage() {}

func (x *ScannerResult) ProtoReflect() protoreflect.Message {
	mi := &file_analyzer_v1_tamga_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScannerResult.ProtoReflect.Descriptor instead.
func (*ScannerResult) Descriptor() ([]byte, []int) {
	return file_analyzer_v1_tamga_proto_rawDescGZIP(), []int{3}
}

func (x *ScannerResult) GetScanner() string {
	if x != nil {
		return x.Scanner
	}
	return ""
}

func (x *ScannerResult) GetFindings() []*Finding {
	if x != nil {
		return x.Findings
	}
	return nil
}

func (x *ScannerResult) GetDurationMs() float64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_analyzer_v1_tamga_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analyzer_v1_tamga_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_analyzer_v1_tamga_proto_rawDescGZIP(), []int{4}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`   // "ok" when healthy
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"` // "tamga-analyzer"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_analyzer_v1_tamga_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analyzer_v1_tamga_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_analyzer_v1_tamga_proto_rawDescGZIP(), []int{5}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

var File_analyzer_v1_tamga_proto protoreflect.FileDescriptor

const file_analyzer_v1_tamga_proto_rawDesc = "" +
	"\n" +
	"\x17analyzer/v1/tamga.proto\x12\x11proto.analyzer.v1\"\xc5\x02\n" +
	"\x0eAnalyzeRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"scan_types\x18\x03 \x03(\tR\tscanTypes\x12\x1a\n" +
	"\bprovider\x18\x04 \x01(\tR\bprovider\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\x12K\n" +
	"\bmetadata\x18\x06 \x03(\v2/.proto.analyzer.v1.AnalyzeRequest.MetadataEntryR\bmetadata\x12\x1f\n" +
	"\vpre_scanned\x18\a \x01(\bR\n" +
	"preScanned\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd4\x01\n" +
	"\x0fAnalyzeResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x126\n" +
	"\bfindings\x18\x02 \x03(\v2\x1a.proto.analyzer.v1.FindingR\bfindings\x12\x1f\n" +
	"\vduration_ms\x18\x03 \x01(\x01R\n" +
	"durationMs\x12I\n" +
	"\x0fscanner_results\x18\x04 \x03(\v2 .proto.analyzer.v1.ScannerResultR\x0escannerResults\"\x8b\x01\n" +
	"\aFinding\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x1a\n" +
	"\bseverity\x18\x03 \x01(\tR\bseverity\x12\x14\n" +
	"\x05match\x18\x04 \x01(\tR\x05match\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x01R\n" +
	"confidence\"\x82\x01\n" +
	"\rScannerResult\x12\x18\n" +
	"\ascanner\x18\x01 \x01(\tR\ascanner\x126\n" +
	"\bfindings\x18\x02 \x03(\v2\x1a.proto.analyzer.v1.FindingR\bfindings\x12\x1f\n" +
	"\vduration_ms\x18\x03 \x01(\x01R\n" +
	"durationMs\"\x14\n" +
	"\x12HealthCheckRequest\"G\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice2\xc1\x01\n" +
	"\x0fAnalyzerService\x12P\n" +
	"\aAnalyze\x12!.proto.analyzer.v1.AnalyzeRequest\x1a\".proto.analyzer.v1.AnalyzeResponse\x12\\\n" +
	"\vHealthCheck\x12%.proto.analyzer.v1.HealthCheckRequest\x1a&.proto.analyzer.v1.HealthCheckResponseB?Z=github.com/yatuk/tamga/proto/analyzer/v1;analyzerv1b\x06proto3"

var (
	file_analyzer_v1_tamga_proto_rawDescOnce sync.Once
	file_analyzer_v1_tamga_proto_rawDescData []byte
)

func file_analyzer_v1_tamga_proto_rawDescGZIP() []byte {
	file_analyzer_v1_tamga_proto_rawDescOnce.Do(func() {
		file_analyzer_v1_tamga_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analyzer_v1_tamga_proto_rawDesc), len(file_analyzer_v1_tamga_proto_rawDesc)))
	})
	return file_analyzer_v1_tamga_proto_rawDescData
}

var file_analyzer_v1_tamga_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_analyzer_v1_tamga_proto_goTypes = []any{
	(*AnalyzeRequest)(nil),      // 0: proto.analyzer.v1.AnalyzeRequest
	(*AnalyzeResponse)(nil),     // 1: proto.analyzer.v1.AnalyzeResponse
	(*Finding)(nil),             // 2: proto.analyzer.v1.Finding
	(*ScannerResult)(nil),       // 3: proto.analyzer.v1.ScannerResult
	(*HealthCheckRequest)(nil),  // 4: proto.analyzer.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 5: proto.analyzer.v1.HealthCheckResponse
	nil,                         // 6: proto.analyzer.v1.AnalyzeRequest.MetadataEntry
}
var file_analyzer_v1_tamga_proto_depIdxs = []int32{
	6, // 0: proto.analyzer.v1.AnalyzeRequest.metadata:type_name -> proto.analyzer.v1.AnalyzeRequest.MetadataEntry
	2, // 1: proto.analyzer.v1.AnalyzeResponse.findings:type_name -> proto.analyzer.v1.Finding
	3, // 2: proto.analyzer.v1.AnalyzeResponse.scanner_results:type_name -> proto.analyzer.v1.ScannerResult
	2, // 3: proto.analyzer.v1.ScannerResult.findings:type_name -> proto.analyzer.v1.Finding
	0, // 4: proto.analyzer.v1.AnalyzerService.Analyze:input_type -> proto.analyzer.v1.AnalyzeRequest
	4, // 5: proto.analyzer.v1.AnalyzerService.HealthCheck:input_type -> proto.analyzer.v1.HealthCheckRequest
	1, // 6: proto.analyzer.v1.AnalyzerService.Analyze:output_type -> proto.analyzer.v1.AnalyzeResponse
	5, // 7: proto.analyzer.v1.AnalyzerService.HealthCheck:output_type -> proto.analyzer.v1.HealthCheckResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_analyzer_v1_tamga_proto_init() }
func file_analyzer_v1_tamga_proto_init() {
	if File_analyzer_v1_tamga_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analyzer_v1_tamga_proto_rawDesc), len(file_analyzer_v1_tamga_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analyzer_v1_tamga_proto_goTypes,
		DependencyIndexes: file_analyzer_v1_tamga_proto_depIdxs,
		MessageInfos:      file_analyzer_v1_tamga_proto_msgTypes,
	}.Build()
	File_analyzer_v1_tamga_proto = out.File
	file_analyzer_v1_tamga_proto_goTypes = nil
	file_analyzer_v1_tamga_proto_depIdxs = nil
}
