# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from classifier.v1 import classifier_pb2 as classifier_dot_v1_dot_classifier__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in classifier/v1/classifier_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ClassifierServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Classify = channel.unary_unary(
                '/proto.classifier.v1.ClassifierService/Classify',
                request_serializer=classifier_dot_v1_dot_classifier__pb2.ClassifyRequest.SerializeToString,
                response_deserializer=classifier_dot_v1_dot_classifier__pb2.ClassifyResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/proto.classifier.v1.ClassifierService/Health',
                request_serializer=classifier_dot_v1_dot_classifier__pb2.HealthRequest.SerializeToString,
                response_deserializer=classifier_dot_v1_dot_classifier__pb2.HealthResponse.FromString,
                _registered_method=True)


class ClassifierServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Classify(self, request, context):
        """Classify scores texts. UNAVAILABLE means no model is loaded.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health reports whether a model is loaded and which one.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClassifierServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Classify': grpc.unary_unary_rpc_method_handler(
                    servicer.Classify,
                    request_deserializer=classifier_dot_v1_dot_classifier__pb2.ClassifyRequest.FromString,
                    response_serializer=classifier_dot_v1_dot_classifier__pb2.ClassifyResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=classifier_dot_v1_dot_classifier__pb2.HealthRequest.FromString,
                    response_serializer=classifier_dot_v1_dot_classifier__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.classifier.v1.ClassifierService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.classifier.v1.ClassifierService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClassifierService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Classify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.classifier.v1.ClassifierService/Classify',
            classifier_dot_v1_dot_classifier__pb2.ClassifyRequest.SerializeToString,
            classifier_dot_v1_dot_classifier__pb2.ClassifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.classifier.v1.ClassifierService/Health',
            classifier_dot_v1_dot_classifier__pb2.HealthRequest.SerializeToString,
            classifier_dot_v1_dot_classifier__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
